version: '3'
services:
  mongo:
    image: 'mongo'
    ports:
      - "27017:27017"
  maps-tool:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "mongo"
