version: '3'
services:
  mongo:
    image: 'mongo'
    ports:
      - "27017:27017"
  maps-tool:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
     - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - "mongo"
